### ISSUE TITLE
[DOCUMENTATION] Modify project technolgoy part of README file

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#11]
@shabiasaeed, can you please modify the README file to modify the layout of the technology section of our project?

**Comment by shabiasaeed** [comment]
I just finished modifying technologies and including the overall layout to make our README more readable and professional.

**Comment by khalidsaadat** [comment]
@shabiasaeed fixed this with: 1c9ef7012f0227abec26f7dec8fcc92a220dd116
