### ISSUE TITLE
[USER STORY] As an admin, I want to add products so that other users can view them on the browsing page.

### ISSUE THREAD

**Issue by JIAYI615** [khalidsaadat/soen341#23]
Once logged in, the admin has the ability to add products.

### Structure 
- **Controller:** 
  - `ProductController`
  - `AdminController`
- **Function Name:** 
  - `add_product` -> Product
  - `index` -> Admin
- **Model:** 
  - `Product`
  - 'Admin`
- **View:** 
  - `products/product_list` 
  - `products/add_product`
  - `admin/index`

**Priority:** High
**Story Point:** 8

### Sub Task:
- [x] #41 
- [x] #43 
- [x] #52

**Comment by khalidsaadat** [comment]
@JIAYI615, for the view, the folder name is not good. Make a new folder `products` and put the view there. `products/product_list` and `products/add_product`

**Comment by khalidsaadat** [comment]
Also @JIAYI615, the controller name is singular, so `ProductController`
