### ISSUE TITLE
Epic user story 1: Browsing items

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#3]
Kindly add at least 4 user stories for the "Browsing items" epic user story.

**Comment by khalidsaadat** [comment]
Once done, open this file [Sprint 1](https://docs.google.com/spreadsheets/d/1W-Vwu8acNQIfLbHaUwlDPs_vttswEiPfjp850s6jMhI/edit#gid=0) and change your task's status to 'DONE'.

**Comment by programer653** [comment]
I have two user stories, tell me what you think about it:
As a normal user, I can scroll down with my mouse to see other items on the bottom of the page
As a normal user, I can click on a product to view the details of the product such as the price and the characteristics.

**Comment by khalidsaadat** [comment]
@programer653, we cannot implement the first user story because scrolling down is already there by the browser.

**Comment by programer653** [comment]
@khalidsaadat no problem, I will another one

**Comment by programer653** [comment]
These are the two user stories that I found: 
As a normal user, I can scroll down with my mouse to see other items on the bottom of the page
As a normal user, I can search for a specific product by writing keywords in relation to this product in the search bar

**Comment by khalidsaadat** [comment]
@programer653, we cannot implement the first user story because we cannot implement scrolling down with the mouse. Scrolling is already there in the browser. The second user story is perfect. If you could fix the first user story, that would be good.

**Comment by asha97** [comment]
Another idea I had is the following: 
As a normal user, I can create a drop down bar in which I could categorize a group of items.

Please let me know if you guys agree with this!

**Comment by pavithrasiv** [comment]
I also thought about this one:
As a normal user, I want to login or register to my account so that I can get more recommendations according to my interests.

**Comment by khalidsaadat** [comment]
> I also thought about this one: As a normal user, I want to login or register to my account so that I can get more recommendations according to my interests.

The recommendation system is really good... but it would require a lot of time.

**Comment by pavithrasiv** [comment]
I thought about another one as well:
As an admin, I want to add products so that other users can view them on the browsing page.

**Comment by programer653** [comment]
> @programer653, we cannot implement the first user story because we cannot implement scrolling down with the mouse. Scrolling is already there in the browser. The second user story is perfect. If you could fix the first user story, that would be good.

Sorry, I just saw my mistake, I edited my reply for the right story issues, I also put it in the sprint breakdown spreadsheet.

**Comment by asha97** [comment]
> Another idea I had is the following: As a normal user, I can create a drop down bar in which I could categorize a group of items.
> 
> Please let me know if you guys agree with this!

@khalidsaadat let me know if this is good.

**Comment by khalidsaadat** [comment]
> 

@asha97, normal user cannot create dropdown menu. An admin, however, can create a dropdown menu.

**Comment by asha97** [comment]
As a normal user, I can look at the products that are in promotion.
@khalidsaadat @pavithrasiv @programer653 please validate this idea.

**Comment by asha97** [comment]
@khalidsaadat @pavithrasiv @programer653 I have added two sub-stories into the document. 

- As a normal user, I want to be able to filter products by category so that I could shop for the right product.
- As a normal user, I want to find a product at a cheaper price so that I could save money.

**Comment by khalidsaadat** [comment]
> @khalidsaadat @pavithrasiv @programer653 I have added two sub-stories into the document.
> 
> * As a normal user, I want to be able to filter products by category so that I could shop for the right product.
> * As a normal user, I want to find a product at a cheaper price so that I could save money.

@asha97, filter products by category user story is amazing. The second user story about promotion, could you change "cheaper price" to "sale"? Like "as a normal user, I can open the sale/promotion page so that I can buy the product at a discounted price."

**Comment by asha97** [comment]
@khalidsaadat done!

**Comment by khalidsaadat** [comment]
Finished epic story 1.
