### ISSUE TITLE
[TASK] Connect Travis CI to Repository and Write Basic Test Case (Setup)

### ISSUE THREAD

**Issue by AnumSidd** [khalidsaadat/soen341#45]
**Description**
Add a continuous integration (CI) service for this project. The goal here is to automate the testing for every release or versions of this project during each iteration.

**Tasks (test out with an exercise)**
Fork from given repo url: https://github.com/peterc-concordia/TravisExercise
Enable connection between Travis and this GitHub repository.
Locally clone the repo
Add a .travis.yml file
Push a change to break the build (in our forked repo) and see if Travis finds it!

**Comment by shabiasaeed** [comment]
GitHub Action has been implemented!
