### ISSUE TITLE
Epic user story 2: Adding products to the cart

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#5]
Kindly add at least 4 user stories for the "Checking out" epic user story.

**Comment by khalidsaadat** [comment]
Once done, open this file [Sprint 1](https://docs.google.com/spreadsheets/d/1W-Vwu8acNQIfLbHaUwlDPs_vttswEiPfjp850s6jMhI/edit#gid=0) and change your task's status to 'DONE'.

**Comment by khalidsaadat** [comment]
What you think about this user story:
As a normal user, I can edit the product so that I can increase/decrease the quantity or remove it from the cart.

**Comment by AnumSidd** [comment]
The two user stories I have in mind are:
1) As a normal user, I can move a product from cart to wish list so that I can look/buy it later.
2) As a normal user, I can add a product to the cart so that I can check the items off my shopping list.

**Comment by shabiasaeed** [comment]
My user story suggestion:
As a normal user, I can see the delivery date so that I can know when to expect the delivery.
