### ISSUE TITLE
[USER STORY] As a normal user, I want to be able to place an order, so that I can purchase the items I want.

### ISSUE THREAD

**Issue by AnumSidd** [khalidsaadat/soen341#68]
### Task:
- [x] #93  
- [x] #111 

### Acceptance Test:

1. User has the ability to access the "Checkout" page.
2. On that page, user can click on "Review Order" to access the review page.
3. On the review page, user has the ability to place the order by clicking "Place Order" button.

**Comment by AnumSidd** [comment]
make sure to display a Thank you message after an order is placed.

**Comment by shabiasaeed** [comment]
Okay yes! I will work on that
