### ISSUE TITLE
[USER STORY] As a normal user, I want to be able to cancel an order, so that I don’t have to pay for the items that are no longer needed.

### ISSUE THREAD

**Issue by AnumSidd** [khalidsaadat/soen341#70]
### Task:
- [x] #92
- [x] #112     

### Objective
After placing an order

### Acceptance Test

1. On order's page, user has access to "Cancel Order" button.
2. Once clicked, the user can cancel their order.

**Comment by shabiasaeed** [comment]
The button is already made on the orders page. What's now is left is to make it function

**Comment by AnumSidd** [comment]
Okay perfect. I will work on that
