### ISSUE TITLE
[USER STORY] As a normal user, I want to be able to submit/edit my billing and payment information, so that I can place my order.

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#73]
### Task:
- [x] #63  
- [x] #97 

### Acceptance Test:

1. User has the ability to access the "Checkout" page.

2. On that page, user can enter their billing details: 

- First Name
- Last Name
- Country
- Address
- Town/City
- Country/State
- Postcode/Zip
- Phone
- Email

3. One the same page, user can enter their payment details:

- Credit/Debit card
- Cardholder name
- Expiration Date
- Security Code

**Comment by AnumSidd** [comment]
@shabiasaeed Don't forget the CVV number for American Express card should validate 4 digits and for the rest it should validate 3 digits.

**Comment by shabiasaeed** [comment]
Noted! thank you for reminding
