### ISSUE TITLE
[SUMMARY] Sprint 3 Meeting Minutes

### ISSUE THREAD

**Issue by shabiasaeed** [khalidsaadat/soen341#77]
**WRAP UP**
- Closing already done user stories/tasks of Sprint 2
- Distribution of tasks for 3rd core feature (Checking Out)
- Making sure to complete remaining of 2nd core feature's user stories/tasks
- Baby registry as an idea for additional feature to propose to the TA and the promotional page as back up

**Comment by AnumSidd** [comment]
As discussed with TA:

We can work on our proposed additional feature which is "Baby Registry".
