### ISSUE TITLE
[TESTING] Create working CI for the project

### ISSUE THREAD

**Issue by khalidsaadat** [khalidsaadat/soen341#78]
**Acceptance Test**

1. Build has to be detected by Github actions
2. For our project, empty tests are available through Github actions

**Comment by khalidsaadat** [comment]
I confirm that the GitHub actions are well connected to this repo.

**Comment by shabiasaeed** [comment]
I just confirmed that the proper settings have been implemented in order for GitHub actions to work properly.

**Comment by shabiasaeed** [comment]
Created! closing now
