### ISSUE TITLE
[DOCUMENTATION] Architecture Block Diagram Consistent with Code.

### ISSUE THREAD

**Issue by AnumSidd** [khalidsaadat/soen341#81]

**Comment by shabiasaeed** [comment]
**Can you all please check if any further modifications are needed?**

![Block Diagram drawio (3)](https://user-images.githubusercontent.com/84743905/158098390-42360270-ffaa-4427-adf1-c76a2a5e98aa.png)

**Comment by AnumSidd** [comment]
This looks great &#128076;. You can upload this block diagram under wiki.

**Comment by khalidsaadat** [comment]
I like the design. It is much more clearer. Thank you
